version: "3.7"


      
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/configs/caddy:/data
      - ${PWD}/Caddyfile:/Caddyfile
    restart: unless-stopped

  whoami:
    image: jwilder/whoami
    container_name: whoami
    networks:
      - caddy
    labels:
      caddy: whoami.madpin.dev
      caddy.reverse_proxy: "{{upstreams 8000}}"


networks:
  caddy:
    name: caddy
    driver: bridge