---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:nightly
    container_name: calibre-web
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${HOME}/configs/calibre/web:/config
      - ${HOME}/calibre_library:/books
    restart: unless-stopped
    labels:
      caddy: library.madpin.dev
      caddy.reverse_proxy: "{{upstreams 8083}}"

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK_SET=022
    volumes:
      - ${HOME}/configs/calibre/desktop:/config
      - ${HOME}/calibre_library:/books
    restart: unless-stopped
    labels:
      caddy: calibre.madpin.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy:
    external:
      name: caddy