---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:nightly
    container_name: calibre-web
    networks:
      - nginx-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - VIRTUAL_HOST=library.madpin.dev
      - VIRTUAL_PORT=8083
    volumes:
      - ${HOME}/configs/calibre/web:/config
      - ${HOME}/calibre_library:/books
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    networks:
      - nginx-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - VIRTUAL_HOST=calibre.madpin.dev
      - VIRTUAL_PORT=8080
    volumes:
      - ${HOME}/configs/calibre/desktop:/config
      - ${HOME}/calibre_library:/books
    restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
