version: "3"
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    user: root
    working_dir: /home/madpin
    container_name: jupyter
    networks:
      - nginx-proxy
    volumes:
      - ${HOME}/ipynbs:/home/madpin
    environment:
      - TZ=Europe/Dublin
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
      - NB_GID=1000
      - NB_UID=1000
      - CHOWN_HOME=yes
      - VIRTUAL_HOST=jupyter.madpin.dev
      - VIRTUAL_PORT=8888
    restart: unless-stopped
    command: >
      start-notebook.sh
      --NotebookApp.password='sha1:47a87a60d69d:e98216612acf96544b2ea28b49bd25db03b58197'
      --ip='*'

networks:
  nginx-proxy:
    external:
      name: nginx-proxy