---
version: '3'
services:
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: unless-stopped
    networks:
      - website-internal
      - caddy
    depends_on:
      - lychee_db
    volumes:
      - ${HOME}/configs/website/lychee:/config
      - ${HOME}/photos:/pictures
    environment:
      - DB_HOST=lychee_db
      - DB_USERNAME=exampleuser
      - DB_PASSWORD=examplepass
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Dublin
      - VIRTUAL_HOST=photos.madpin.dev
    labels:
      caddy: photos.madpin.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

  lychee_db:
    image: mysql:5.7
    user: '1000:1000'
    container_name: lychee_db
    restart: unless-stopped
    command:
      - '--ignore-db-dir=lost+found --initialize-insecure'
    networks:
      - website-internal
    environment:
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ROOT_PASSWORD=random_password
    volumes:
      - ${HOME}/configs/website/lychee_db:/var/lib/mysql


  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    user: '1000:1000'
    networks:
      - website-internal
      - caddy
    depends_on:
      - wordpress_db
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=wordpress
      - VIRTUAL_HOST=madpin.dev
    volumes:
      - ${HOME}/configs/website/wordpress:/var/www/html
    labels:
      caddy: madpin.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

  wordpress_db:
    image: mysql:5.7
    user: '1000:1000'
    container_name: wordpress_db
    restart: unless-stopped
    command:
      - '--ignore-db-dir=lost+found --initialize-insecure'
    networks:
      - website-internal
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ROOT_PASSWORD=random_password
    volumes:
      - ${HOME}/configs/website/wordpress_db:/var/lib/mysql


networks:
  caddy:
    external:
      name: caddy
  website-internal:
    name: website-internal
    driver: bridge